/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.lyne.idl.protocol;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserInfoType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5535936323750353952L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserInfoType\",\"namespace\":\"org.lyne.idl.protocol\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"addr\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"city\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserInfoType> ENCODER =
      new BinaryMessageEncoder<UserInfoType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserInfoType> DECODER =
      new BinaryMessageDecoder<UserInfoType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserInfoType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserInfoType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserInfoType>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserInfoType to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserInfoType from a ByteBuffer. */
  public static UserInfoType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int age;
  @Deprecated public java.util.List<org.lyne.idl.protocol.Address> addr;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserInfoType() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param age The new value for age
   * @param addr The new value for addr
   */
  public UserInfoType(java.lang.Integer id, java.lang.CharSequence name, java.lang.Integer age, java.util.List<org.lyne.idl.protocol.Address> addr) {
    this.id = id;
    this.name = name;
    this.age = age;
    this.addr = addr;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return age;
    case 3: return addr;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: addr = (java.util.List<org.lyne.idl.protocol.Address>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'addr' field.
   * @return The value of the 'addr' field.
   */
  public java.util.List<org.lyne.idl.protocol.Address> getAddr() {
    return addr;
  }

  /**
   * Sets the value of the 'addr' field.
   * @param value the value to set.
   */
  public void setAddr(java.util.List<org.lyne.idl.protocol.Address> value) {
    this.addr = value;
  }

  /**
   * Creates a new UserInfoType RecordBuilder.
   * @return A new UserInfoType RecordBuilder
   */
  public static org.lyne.idl.protocol.UserInfoType.Builder newBuilder() {
    return new org.lyne.idl.protocol.UserInfoType.Builder();
  }

  /**
   * Creates a new UserInfoType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserInfoType RecordBuilder
   */
  public static org.lyne.idl.protocol.UserInfoType.Builder newBuilder(org.lyne.idl.protocol.UserInfoType.Builder other) {
    return new org.lyne.idl.protocol.UserInfoType.Builder(other);
  }

  /**
   * Creates a new UserInfoType RecordBuilder by copying an existing UserInfoType instance.
   * @param other The existing instance to copy.
   * @return A new UserInfoType RecordBuilder
   */
  public static org.lyne.idl.protocol.UserInfoType.Builder newBuilder(org.lyne.idl.protocol.UserInfoType other) {
    return new org.lyne.idl.protocol.UserInfoType.Builder(other);
  }

  /**
   * RecordBuilder for UserInfoType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserInfoType>
    implements org.apache.avro.data.RecordBuilder<UserInfoType> {

    private int id;
    private java.lang.CharSequence name;
    private int age;
    private java.util.List<org.lyne.idl.protocol.Address> addr;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.lyne.idl.protocol.UserInfoType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.addr)) {
        this.addr = data().deepCopy(fields()[3].schema(), other.addr);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserInfoType instance
     * @param other The existing instance to copy.
     */
    private Builder(org.lyne.idl.protocol.UserInfoType other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.addr)) {
        this.addr = data().deepCopy(fields()[3].schema(), other.addr);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'addr' field.
      * @return The value.
      */
    public java.util.List<org.lyne.idl.protocol.Address> getAddr() {
      return addr;
    }

    /**
      * Sets the value of the 'addr' field.
      * @param value The value of 'addr'.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder setAddr(java.util.List<org.lyne.idl.protocol.Address> value) {
      validate(fields()[3], value);
      this.addr = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'addr' field has been set.
      * @return True if the 'addr' field has been set, false otherwise.
      */
    public boolean hasAddr() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'addr' field.
      * @return This builder.
      */
    public org.lyne.idl.protocol.UserInfoType.Builder clearAddr() {
      addr = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserInfoType build() {
      try {
        UserInfoType record = new UserInfoType();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.addr = fieldSetFlags()[3] ? this.addr : (java.util.List<org.lyne.idl.protocol.Address>) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserInfoType>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserInfoType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserInfoType>
    READER$ = (org.apache.avro.io.DatumReader<UserInfoType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
